## This file is a list of things to be downloaded using the command:
#   run.py download

# To add a new item to be download, add a block like this - must have 'url',
# 'local_name' is optional, use to avoid name collisions

#  #
#  # Description of source
#  #
#  -
#    # brief comment about file, and optionally a local_name:
#    url: http://curefordisease.org/some_data.txt
#    local_name: some_data_more_chars_prevent_name_collision.pdf
#
#  For downloading from S3 buckets, see here for information about what URL to use:
#  https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro
#  Amazon S3 virtual hosted style URLs follow the format shown below:
#  https://bucket-name.s3.Region.amazonaws.com/key_name
#
---

#
# **** ROBOT ****
#
-
  url: https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar
  local_name: robot.jar
-
  url: https://raw.githubusercontent.com/ontodev/robot/master/bin/robot 
  local_name: robot

# **** Ontology files ****
#
# ENVO
#
-
  url: http://purl.obolibrary.org/obo/envo.json
  local_name: envo.json

# NCBITaxon
#
-
  url: http://purl.obolibrary.org/obo/ncbitaxon.owl.gz
  local_name: ncbitaxon.owl.gz

#
# ChEBI
#
-
  url: http://purl.obolibrary.org/obo/chebi.owl.gz
  local_name: chebi.owl.gz

#
# Go-Plus
#
-
  url: http://purl.obolibrary.org/obo/go/extensions/go-plus.json
  local_name: go-plus.json

#
# MONDO
#
-
  url: http://purl.obolibrary.org/obo/mondo.json
  local_name: mondo.json

#
# HPO
#
-
  url: http://purl.obolibrary.org/obo/hp.json
  local_name: hp.json


# #
# # GO
# #
# -
#   url: http://purl.obolibrary.org/obo/go.json
#   local_name: go.json


# **** Data sources ****
# ATC
# The Anatomical Therapeutic Chemical Classification for drugs
# Primarily for establishing hierarchical relationships of DrugCentral entries
# -
#   url: https://data.bioontology.org/ontologies/ATC/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb&download_format=csv
#   local_name: atc.csv.gz

# BacDive
# Explore Bacterial Diversity
-
  url: gdrive:1dOquB0M6H5Vxu6cBPa4kJ7F9v44medoV
  local_name: bacdive_strains.json

# MediaDive
# Explore MediaDive data
-
  url: https://mediadive.dsmz.de/rest/media
  local_name: mediadive.json

# Condensed-traits
# - GTDB
#   link: https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/blob/master/output/condensed_traits_GTDB.csv
#-
#  url: https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/blob/master/output/condensed_traits_GTDB.csv?raw=true
#  local_name: condensed_traits_GTDB.csv
# - NCBI
#   link: https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/tree/master/output
-
  url: https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/blob/master/output/condensed_traits_NCBI.csv?raw=true
  local_name: traits.csv

# # ****Conversion Tables****
#
# Environment
#
-
  url: https://raw.githubusercontent.com/bacteria-archaea-traits/bacteria-archaea-traits/master/data/conversion_tables/environments.csv
  local_name: environments.csv

#
# KEGG-Compound-CHEBI
#
-
  url: https://rest.kegg.jp/conv/chebi/cpd
  local_name: kegg-cpd-chebi.tsv

#
# KEGG-Compound-Reaction
#
-
  url: https://rest.kegg.jp/link/rn/cpd
  local_name: kegg-cpd-rxn.tsv

#
# KEGG-Compound-Pathway
#
-
  url: https://rest.kegg.jp/link/pathway/cpd
  local_name: kegg-cpd-pathway.tsv

#
# KEGG-Reaction-Pathway
#
-
  url: https://rest.kegg.jp/link/pathway/rn
  local_name: kegg-rxn-pathway.tsv

#
# Uniprot
#

- base_url: https://rest.uniprot.org/uniprotkb/
  api: rest
  url: 'gdrive:1Ai52w4fu4XPu5w4wdE8y3rymEgN0BDqe'
  local_name: 'uniprot_genome_features'
  fields: [
    "organism_id",
    "id", 
    "accession",
    "protein_name",
    "ec",
    "ft_binding"
  ]
  keywords: [
    "Reference+proteome"
  ]
  size: 500
  batch_size: 1
  test: True

#Metanetx 

-
  url: http://metanetx.org/cgi-bin/mnxget/mnxref/chem_xref.tsv
  local_name: chem_xref.tsv
-
  url: http://metanetx.org/cgi-bin/mnxget/mnxref/reac_xref.tsv
  local_name: reac_xref.tsv
-
  url: http://metanetx.org/cgi-bin/mnxget/mnxref/chem_prop.tsv
  local_name: chem_prop.tsv
-
  url: http://metanetx.org/cgi-bin/mnxget/mnxref/reac_prop.tsv
  local_name: reac_prop.tsv


#Rhea

- 
  url: https://ftp.expasy.org/databases/rhea/tsv/rhea2uniprot%5Fsprot.tsv
  local_name: rhea2uniprot_sprot.tsv
- 
  url: https://ftp.expasy.org/databases/rhea/tsv/rhea2go.tsv
  local_name: rhea2go.tsv
