site_name: KG-Microbe
repo_name: KG-Microbe
theme: 
    name: readthedocs
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
repo_url: https://github.com/Knowledge-Graph-Hub/kg-microbe/
edit_uri: blob/master/docs/
nav:
    - Home: index.md

