-- The schema a real `semsql make` emits, captured from a shipped database.
-- Kept as data rather than a Python literal: it is 100 statements long, it is
-- not meant to be edited by hand, and hand-written partial shapes drifted from
-- the production gate three rounds running.
-- Regenerate with:
--   sqlite3 data/raw/ec.db ".schema" > tests/semsql_schema.sql

CREATE VIEW all_problems AS SELECT * FROM node_with_two_labels_problem UNION SELECT * FROM trailing_whitespace_problem;
CREATE VIEW annotation_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:AnnotationProperty';
CREATE VIEW asymmetric_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:AsymmetricProperty';
CREATE VIEW axiom_dbxref_annotation AS SELECT * FROM owl_axiom_annotation WHERE annotation_predicate = 'oio:hasDbXref';
CREATE VIEW blank_node AS SELECT * FROM node WHERE id LIKE '_:%';
CREATE VIEW class_node AS SELECT distinct subject AS id from rdf_type_statement WHERE object = 'owl:Class';
CREATE VIEW contributor AS SELECT * FROM statements WHERE predicate='dcterms:contributor';
CREATE VIEW count_of_instantiated_classes AS SELECT object AS element, count(*) AS count_value FROM rdf_type_statement GROUP BY element ORDER BY count_value DESC;
CREATE VIEW count_of_predicates AS SELECT predicate AS element, count(*) AS count_value FROM statements GROUP BY predicate ORDER BY count_value DESC;
CREATE VIEW count_of_subclasses AS SELECT sc.object AS element, count(distinct sc.subject) AS count_value FROM rdfs_subclass_of_statement AS sc GROUP BY sc.object ORDER BY count_value DESC;
CREATE VIEW creator AS SELECT * FROM statements WHERE predicate='dcterms:creator';
CREATE VIEW deprecated_node AS SELECT DISTINCT subject AS id FROM statements WHERE predicate='owl:deprecated' AND value='true';
CREATE VIEW edge AS SELECT subject, predicate, object FROM owl_subclass_of_some_values_from UNION SELECT subject, predicate, object FROM rdfs_subclass_of_named_statement UNION SELECT subject, predicate, object FROM rdfs_subproperty_of_statement UNION SELECT subject, predicate, object FROM rdf_type_statement WHERE object IN (SELECT id FROM class_node);
CREATE VIEW entailed_edge_cycle AS SELECT e.*, e2.predicate AS secondary_predicate FROM entailed_edge AS e, entailed_edge AS e2 WHERE e.object = e2.subject AND e2.object=e.subject;
CREATE VIEW entailed_edge_same_predicate_cycle AS SELECT * FROM entailed_edge_cycle WHERE predicate = secondary_predicate;
CREATE VIEW entailed_subclass_of_edge AS SELECT * FROM entailed_edge WHERE predicate='rdfs:subClassOf';
CREATE VIEW entailed_type_edge AS SELECT * FROM entailed_edge WHERE predicate='rdf:type';
CREATE VIEW has_broad_match_statement AS SELECT * FROM statements WHERE predicate='skos:hasBroadMatch';
CREATE VIEW has_broad_synonym_statement AS SELECT * FROM statements WHERE predicate='oio:hasBroadSynonym';
CREATE VIEW has_dbxref_statement AS SELECT * FROM statements WHERE predicate='oio:hasDbXref';
CREATE VIEW has_exact_match_statement AS SELECT * FROM statements WHERE predicate='skos:hasExactMatch';
CREATE VIEW has_exact_synonym_statement AS SELECT * FROM statements WHERE predicate='oio:hasExactSynonym';
CREATE VIEW has_mapping_statement AS SELECT * FROM has_match_statement UNION SELECT * FROM has_dbxref_statement;
CREATE VIEW has_match_statement AS SELECT * FROM has_exact_match_statement UNION SELECT * FROM has_broad_match_statement UNION SELECT * FROM has_narrow_match_statement UNION SELECT * FROM has_related_match_statement;
CREATE VIEW has_narrow_match_statement AS SELECT * FROM statements WHERE predicate='skos:hasNarrowMatch';
CREATE VIEW has_narrow_synonym_statement AS SELECT * FROM statements WHERE predicate='oio:hasNarrowSynonym';
CREATE VIEW has_related_match_statement AS SELECT * FROM statements WHERE predicate='skos:hasRelatedMatch';
CREATE VIEW has_related_synonym_statement AS SELECT * FROM statements WHERE predicate='oio:hasRelatedSynonym';
CREATE VIEW has_synonym_statement AS SELECT * FROM has_exact_synonym_statement UNION SELECT * FROM has_broad_synonym_statement UNION SELECT * FROM has_narrow_synonym_statement UNION SELECT * FROM has_related_synonym_statement;
CREATE VIEW has_text_definition_statement AS SELECT * FROM statements WHERE predicate='IAO:0000115';
CREATE VIEW iri_node AS SELECT * FROM node WHERE id NOT LIKE '_:%';
CREATE VIEW irreflexive_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:ReflexiveProperty';
CREATE VIEW named_individual_node AS SELECT distinct subject AS id from rdf_type_statement WHERE object = 'owl:NamedIndividual';
CREATE VIEW node AS SELECT distinct(subject) AS id FROM statements UNION SELECT distinct(object) AS id FROM statements WHERE datatype IS NOT NULL;
CREATE VIEW node_identifier AS SELECT id AS id, substr(id,0, instr(id,':')) AS prefix, substr(id,instr(id,':')+1) AS local_identifier FROM node;
CREATE VIEW node_to_node_statement AS SELECT * FROM statements WHERE object IS NOT NULL;
CREATE VIEW node_to_value_statement AS SELECT * FROM statements WHERE value IS NOT NULL;
CREATE VIEW node_with_two_labels_problem AS SELECT s1.subject, s1.predicate, s1.value FROM rdfs_label_statement AS s1, rdfs_label_statement AS s2 WHERE s1.subject=s2.subject AND s1.value != s2.value;
CREATE VIEW object_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:ObjectProperty';
CREATE VIEW ontology_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:Ontology';
CREATE VIEW ontology_status_statement AS SELECT * FROM statements WHERE predicate = '<http://obofoundry.github.io/vocabulary/activity_status>' UNION SELECT * FROM statements WHERE predicate = 'pav:status';
CREATE VIEW orcid AS SELECT subject AS id, value AS label FROM rdfs_label_statement WHERE subject like 'orcid:%';
CREATE VIEW owl_all_values_from AS SELECT onProperty.subject AS id, onProperty.object AS on_property, f.object AS filler FROM statements AS onProperty, statements AS f WHERE onProperty.predicate = 'owl:onProperty' AND onProperty.subject=f.subject AND f.predicate='owl:allValuesFrom';
CREATE VIEW owl_axiom AS SELECT * FROM owl_reified_axiom UNION SELECT NULL AS id, * FROM statements;
CREATE VIEW owl_axiom_annotation AS SELECT axpv.stanza AS stanza, axs.object AS subject, axp.object AS predicate, axo.object AS object, axo.value AS value, axo.datatype AS datatype, axo.language AS language, axpv.subject AS id, axpv.subject AS annotation_subject, axpv.predicate AS annotation_predicate, axpv.object AS annotation_object, axpv.value AS annotation_value, axpv.language AS annotation_language, axpv.datatype AS annotation_datatype FROM statements AS axs, statements AS axp, statements AS axo, statements AS axpv WHERE axs.predicate = 'owl:annotatedSource' AND axp.predicate = 'owl:annotatedProperty' AND axo.predicate = 'owl:annotatedTarget' AND axs.subject = axpv.subject AND axp.subject = axpv.subject AND axo.subject = axpv.subject AND axpv.predicate NOT IN ('owl:annotatedSource', 'owl:annotatedProperty', 'owl:annotatedTarget', 'rdf:type');
CREATE VIEW owl_complement_of_statement AS SELECT * FROM statements WHERE predicate='owl:complementOf';
CREATE VIEW owl_disjoint_class_statement AS SELECT * FROM statements WHERE predicate='owl:disjointWith';
CREATE VIEW owl_equivalent_class_statement AS SELECT * FROM statements WHERE predicate='owl:equivalentClass';
CREATE VIEW owl_equivalent_to_intersection_member AS SELECT e.stanza, e.subject, m.object FROM owl_equivalent_class_statement AS e JOIN statements AS i ON (e.object=i.subject) JOIN rdf_list_member_statement AS m ON (i.object=m.subject) WHERE i.predicate = 'owl:intersectionOf';
CREATE VIEW owl_has_self AS SELECT onProperty.subject AS id, onProperty.object AS on_property, f.object AS filler FROM statements AS onProperty, statements AS f WHERE onProperty.predicate = 'owl:onProperty' AND onProperty.subject=f.subject AND f.predicate='owl:hasSelf' AND f.value='true';
CREATE VIEW owl_has_value AS SELECT onProperty.subject AS id, onProperty.object AS on_property, f.object AS filler FROM statements AS onProperty, statements AS f WHERE onProperty.predicate = 'owl:onProperty' AND onProperty.subject=f.subject AND f.predicate='owl:hasValue';
CREATE VIEW owl_imports_statement AS SELECT * FROM statements WHERE predicate='owl:imports';
CREATE VIEW owl_inverse_of_statement AS SELECT * FROM statements WHERE predicate='owl:inverseOf';
CREATE VIEW owl_reified_axiom AS SELECT axs.subject AS id, axs.stanza AS stanza, axs.object AS subject, axp.object AS predicate, axo.object AS object, axo.value AS value, axo.datatype AS datatype, axo.language AS language FROM statements AS axs, statements AS axp, statements AS axo WHERE axs.predicate = 'owl:annotatedSource' AND axp.predicate = 'owl:annotatedProperty' AND axo.predicate = 'owl:annotatedTarget' AND axs.subject = axp.subject AND axs.subject = axo.subject;
CREATE VIEW owl_same_as_statement AS SELECT * FROM statements WHERE predicate='owl:sameAs';
CREATE VIEW owl_some_values_from AS SELECT onProperty.subject AS id, onProperty.object AS on_property, f.object AS filler FROM statements AS onProperty, statements AS f WHERE onProperty.predicate = 'owl:onProperty' AND onProperty.subject=f.subject AND f.predicate='owl:someValuesFrom';
CREATE VIEW owl_subclass_of_some_values_from AS SELECT subClassOf.stanza, subClassOf.subject, svf.on_property AS predicate, svf.filler AS object FROM statements AS subClassOf, owl_some_values_from AS svf WHERE subClassOf.predicate = 'rdfs:subClassOf' AND svf.id=subClassOf.object;
CREATE VIEW property_node AS SELECT distinct subject AS id from rdf_type_statement WHERE object = 'owl:Property';
CREATE VIEW property_used_with_datatype_values_and_objects AS SELECT DISTINCT s1.predicate AS subject, s1.predicate, s1.datatype AS value FROM statements AS s1, statements AS s2 ON (s1.predicate=s2.predicate) WHERE s1.value IS NOT NULL and s2.object IS NOT NULL;
CREATE VIEW rdf_first_statement AS SELECT * FROM statements WHERE predicate='rdf:first';
CREATE VIEW rdf_list_member_statement AS SELECT rest_t.subject, f.object FROM rdf_rest_transitive_statement AS rest_t JOIN rdf_first_statement AS f ON (rest_t.object = f.subject) UNION SELECT subject,object FROM rdf_first_statement;
CREATE VIEW rdf_list_node AS SELECT distinct subject AS id from rdf_type_statement WHERE object = 'rdf:List';
CREATE VIEW rdf_rest_statement AS SELECT * FROM statements WHERE predicate='rdf:rest';
CREATE VIEW rdf_rest_transitive_statement AS WITH RECURSIVE rdf_rest_transitive_statement ( subject, object ) AS (SELECT subject, object FROM rdf_rest_statement UNION ALL SELECT rest.subject, rest_t.object FROM rdf_rest_statement AS rest JOIN rdf_rest_transitive_statement AS rest_t ON rest.object = rest_t.subject ) SELECT * FROM rdf_rest_transitive_statement;
CREATE VIEW rdf_type_statement AS SELECT * FROM statements WHERE predicate='rdf:type';
CREATE VIEW rdfs_domain_statement AS SELECT * FROM statements WHERE predicate='rdfs:domain';
CREATE VIEW rdfs_label_statement AS SELECT * FROM statements WHERE predicate='rdfs:label';
CREATE VIEW rdfs_range_statement AS SELECT * FROM statements WHERE predicate='rdfs:range';
CREATE VIEW rdfs_subclass_of_named_statement AS SELECT * FROM rdfs_subclass_of_statement WHERE object NOT LIKE '_:%';
CREATE VIEW rdfs_subclass_of_statement AS SELECT * FROM statements WHERE predicate='rdfs:subClassOf';
CREATE VIEW rdfs_subproperty_of_statement AS SELECT * FROM statements WHERE predicate='rdfs:subPropertyOf';
CREATE VIEW reflexive_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:IrreflexiveProperty';
CREATE VIEW subgraph_edge_by_ancestor AS SELECT edge.*, ee.predicate AS anchor_predicate, ee.object AS anchor_object FROM edge JOIN entailed_edge AS ee ON (edge.subject = ee.subject);
CREATE VIEW subgraph_edge_by_ancestor_or_descendant AS SELECT * FROM subgraph_edge_by_ancestor UNION SELECT * FROM subgraph_edge_by_descendant;
CREATE VIEW subgraph_edge_by_child AS SELECT edge.*, ee.predicate AS anchor_predicate, ee.subject AS anchor_object FROM edge JOIN edge AS ee ON (edge.subject = ee.object);
CREATE VIEW subgraph_edge_by_descendant AS SELECT edge.*, ee.predicate AS anchor_predicate, ee.subject AS anchor_object FROM edge JOIN entailed_edge AS ee ON (edge.subject = ee.object);
CREATE VIEW subgraph_edge_by_parent AS SELECT edge.*, ee.predicate AS anchor_predicate, ee.object AS anchor_object FROM edge JOIN edge AS ee ON (edge.subject = ee.subject);
CREATE VIEW subgraph_edge_by_self AS SELECT edge.*, edge.predicate AS anchor_predicate, edge.subject AS anchor_object FROM edge;
CREATE VIEW symmetric_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:SymmetricProperty';
CREATE VIEW trailing_whitespace_problem AS SELECT subject, predicate, value FROM statements WHERE VALUE like ' %' OR VALUE like '% ';
CREATE VIEW transitive_edge AS WITH RECURSIVE transitive_edge ( subject, predicate, object, depth ) AS (SELECT subject, predicate, object, 1 FROM edge UNION ALL SELECT e.subject, e.predicate, a.object, a.depth+1 FROM edge AS e JOIN transitive_edge AS a ON e.object = a.subject AND e.predicate = a.predicate ) SELECT * FROM transitive_edge;
CREATE VIEW transitive_property_node AS SELECT DISTINCT subject AS id FROM rdf_type_statement WHERE object='owl:TransitiveProperty';
CREATE TABLE anonymous_class_expression ( id TEXT NOT NULL, PRIMARY KEY (id) );
CREATE TABLE anonymous_expression ( id TEXT NOT NULL, PRIMARY KEY (id) );
CREATE TABLE anonymous_individual_expression ( id TEXT NOT NULL, PRIMARY KEY (id) );
CREATE TABLE anonymous_property_expression ( id TEXT NOT NULL, PRIMARY KEY (id) );
CREATE TABLE entailed_edge ( subject TEXT, predicate TEXT, object TEXT );
CREATE TABLE has_oio_synonym_statement ( subject TEXT, predicate TEXT, object TEXT, value TEXT NOT NULL, datatype TEXT, language TEXT );
CREATE TABLE lexical_problem ( subject TEXT, predicate TEXT, value TEXT );
CREATE TABLE owl_complex_axiom ( subject TEXT, predicate TEXT, object TEXT );
CREATE TABLE owl_restriction ( on_property TEXT, filler TEXT, id TEXT NOT NULL, PRIMARY KEY (id) );
CREATE TABLE prefix ( prefix TEXT, base TEXT );
CREATE TABLE problem ( subject TEXT, predicate TEXT, value TEXT );
CREATE TABLE rdf_level_summary_statistic ( element TEXT, count_value INTEGER );
CREATE TABLE rdf_list_statement ( subject TEXT, predicate TEXT, object TEXT, value TEXT, datatype TEXT, language TEXT );
CREATE TABLE relation_graph_construct ( subject TEXT, predicate TEXT, object TEXT );
CREATE TABLE repair_action ( subject TEXT, description TEXT );
CREATE TABLE statements (stanza TEXT,subject TEXT,predicate TEXT,object TEXT,value TEXT,datatype TEXT,language TEXT, graph TEXT);
CREATE TABLE subgraph_query ( subject TEXT, predicate TEXT, object TEXT, anchor_object TEXT, anchor_predicate TEXT );
CREATE TABLE term_association ( id TEXT NOT NULL, subject TEXT, predicate TEXT, object TEXT, evidence_type TEXT, publication TEXT, source TEXT, PRIMARY KEY (id) );
