name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Set up Python 3.
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.10

    - name: Install Poetry.
      run: |
        pipx install poetry
        pipx inject poetry poetry-dynamic-versioning

    - name: Install dependencies.
      run: |
        poetry add setuptools@latest
        poetry install --all-extras --with docs
        
    - name: Build documentation.
      run: |
        echo ${{ secrets.GH_TOKEN }} >> kg_microbe/token.txt
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run sphinx-apidoc -o . ../kg_microbe/ --ext-autodoc -f
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/
    
    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        force: true
        folder: gh-pages
