name: Release

on:
  # push:
  #   tags:
  #     - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Zip transformed directory
        run: zip -r transformed.zip data/transformed

    #   - name: Copy merged-kg.tar.gz
    #     run: cp data/merged/merged-kg.tar.gz .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: transformed.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
