name: Uniprot to S3

on:
#   schedule:
#     - cron: '0 0 1 * *' # Runs on the 1st of every month at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for accurate versioning
      
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction --all-extras --no-root

      - name: Install additional dependencies
        run: poetry install --with s3

      # - name: Fetch data from Uniprot API
      #   run: |
      #     kg download
      #     kg transform -s OntologyTransform
      #     kg get-via-api -a uniprot
      
      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync data/raw/uniprot/s3 s3://${{ secrets.AWS_BUCKET_NAME }} --delete

